import 'package:hive_flutter/hive_flutter.dart';
import '../models/menu_item.dart';
import '../models/order.dart';
import '../models/order_line.dart';
import '../models/printer_config.dart';
import '../models/app_config.dart';
import 'api_service.dart';

class StorageService {
  static final StorageService _instance = StorageService._internal();
  factory StorageService() => _instance;
  StorageService._internal();

  Box<MenuItem>? _menuItemsBox;
  Box<Order>? _ordersBox;
  Box<PrinterConfig>? _printerConfigBox;
  Box<AppConfig>? _appConfigBox;
  Box<List<OrderLine>>? _currentOrderBox;

  Future<void> initialize() async {
    await Hive.initFlutter();

    // Register adapters - generated by build_runner
    if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(MenuItemAdapter());
    if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(OrderLineAdapter());
    if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(OrderAdapter());
    if (!Hive.isAdapterRegistered(4))
      Hive.registerAdapter(PrinterConfigAdapter());
    if (!Hive.isAdapterRegistered(5)) Hive.registerAdapter(AppConfigAdapter());

    _menuItemsBox = await Hive.openBox<MenuItem>('menu_items');
    _ordersBox = await Hive.openBox<Order>('orders');
    _printerConfigBox = await Hive.openBox<PrinterConfig>('printer_config');
    _appConfigBox = await Hive.openBox<AppConfig>('app_config');
    _currentOrderBox = await Hive.openBox<List<OrderLine>>('current_order');

    // Clear all data for fresh start every time
    await _clearAllData();

    // Initialize default data
    await _initializeDefaultData();
  }

  Future<void> _clearAllData() async {
    // Only clear current order, keep menu items so app works when backend is offline
    await _currentOrderBox?.clear();
    // DO NOT clear menu items - they serve as fallback when API fails
  }

  Future<void> _initializeDefaultData() async {
    // Seed menu items if empty
    if (_menuItemsBox!.isEmpty) {
      final defaultItems = [
        // Plain Dosas
        MenuItem(id: '1', name: 'Plain Dosa', price: 40.0, category: 'Dosa'),
        MenuItem(
          id: '2',
          name: 'Crispy Plain Dosa',
          price: 45.0,
          category: 'Dosa',
        ),
        // Masala Dosas
        MenuItem(id: '3', name: 'Masala Dosa', price: 60.0, category: 'Dosa'),
        MenuItem(
          id: '4',
          name: 'Crispy Masala Dosa',
          price: 65.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '5',
          name: 'Butter Masala Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        // Cheese Dosas
        MenuItem(id: '6', name: 'Cheese Dosa', price: 80.0, category: 'Dosa'),
        MenuItem(
          id: '7',
          name: 'Cheese Masala Dosa',
          price: 90.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '8',
          name: 'Cheese Onion Dosa',
          price: 85.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '9',
          name: 'Cheese Chilli Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '10',
          name: 'Cheese Garlic Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '11',
          name: 'Cheese Schezwan Dosa',
          price: 100.0,
          category: 'Dosa',
        ),
        // Onion Dosas
        MenuItem(id: '12', name: 'Onion Dosa', price: 50.0, category: 'Dosa'),
        MenuItem(
          id: '13',
          name: 'Onion Masala Dosa',
          price: 65.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '14',
          name: 'Onion Chilli Dosa',
          price: 60.0,
          category: 'Dosa',
        ),
        // Rava Dosas
        MenuItem(id: '15', name: 'Rava Dosa', price: 55.0, category: 'Dosa'),
        MenuItem(
          id: '16',
          name: 'Rava Masala Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '17',
          name: 'Rava Onion Dosa',
          price: 65.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '18',
          name: 'Rava Cheese Dosa',
          price: 85.0,
          category: 'Dosa',
        ),
        // Special Dosas
        MenuItem(
          id: '19',
          name: 'Mysore Masala Dosa',
          price: 75.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '20',
          name: 'Mysore Plain Dosa',
          price: 50.0,
          category: 'Dosa',
        ),
        MenuItem(id: '21', name: 'Paper Dosa', price: 50.0, category: 'Dosa'),
        MenuItem(
          id: '22',
          name: 'Paper Masala Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '23',
          name: 'Set Dosa (3 pcs)',
          price: 60.0,
          category: 'Dosa',
        ),
        MenuItem(id: '24', name: 'Kal Dosa', price: 45.0, category: 'Dosa'),
        // Ghee Dosas
        MenuItem(id: '25', name: 'Ghee Dosa', price: 65.0, category: 'Dosa'),
        MenuItem(
          id: '26',
          name: 'Ghee Masala Dosa',
          price: 80.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '27',
          name: 'Ghee Onion Dosa',
          price: 75.0,
          category: 'Dosa',
        ),
        // Chutney Dosas
        MenuItem(id: '28', name: 'Chutney Dosa', price: 50.0, category: 'Dosa'),
        MenuItem(
          id: '29',
          name: 'Chutney Masala Dosa',
          price: 65.0,
          category: 'Dosa',
        ),
        // Pav Bhaji Dosa
        MenuItem(
          id: '30',
          name: 'Pav Bhaji Dosa',
          price: 90.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '31',
          name: 'Pav Bhaji Masala Dosa',
          price: 100.0,
          category: 'Dosa',
        ),
        // Spring Roll Dosa
        MenuItem(
          id: '32',
          name: 'Spring Roll Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        // Chinese Dosas
        MenuItem(id: '33', name: 'Chinese Dosa', price: 85.0, category: 'Dosa'),
        MenuItem(
          id: '34',
          name: 'Chinese Noodles Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '35',
          name: 'Manchurian Dosa',
          price: 90.0,
          category: 'Dosa',
        ),
        // Schezwan Dosas
        MenuItem(
          id: '36',
          name: 'Schezwan Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '37',
          name: 'Schezwan Masala Dosa',
          price: 85.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '38',
          name: 'Schezwan Cheese Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        // Chilli Dosas
        MenuItem(id: '39', name: 'Chilli Dosa', price: 65.0, category: 'Dosa'),
        MenuItem(
          id: '40',
          name: 'Chilli Cheese Dosa',
          price: 85.0,
          category: 'Dosa',
        ),
        // Podi Dosas
        MenuItem(id: '41', name: 'Podi Dosa', price: 50.0, category: 'Dosa'),
        MenuItem(
          id: '42',
          name: 'Podi Masala Dosa',
          price: 65.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '43',
          name: 'Ghee Podi Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        // Palak Dosas
        MenuItem(id: '44', name: 'Palak Dosa', price: 60.0, category: 'Dosa'),
        MenuItem(
          id: '45',
          name: 'Palak Masala Dosa',
          price: 75.0,
          category: 'Dosa',
        ),
        // Wheat Dosas
        MenuItem(id: '46', name: 'Wheat Dosa', price: 50.0, category: 'Dosa'),
        MenuItem(
          id: '47',
          name: 'Wheat Masala Dosa',
          price: 65.0,
          category: 'Dosa',
        ),
        // Adai Dosa
        MenuItem(id: '48', name: 'Adai Dosa', price: 55.0, category: 'Dosa'),
        MenuItem(
          id: '49',
          name: 'Adai Masala Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        // Neer Dosa
        MenuItem(id: '50', name: 'Neer Dosa', price: 50.0, category: 'Dosa'),
        // Paneer Dosas
        MenuItem(id: '51', name: 'Paneer Dosa', price: 90.0, category: 'Dosa'),
        MenuItem(
          id: '52',
          name: 'Paneer Masala Dosa',
          price: 100.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '53',
          name: 'Paneer Onion Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '54',
          name: 'Paneer Cheese Dosa',
          price: 110.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '55',
          name: 'Paneer Butter Dosa',
          price: 105.0,
          category: 'Dosa',
        ),
        // Mushroom Dosas
        MenuItem(
          id: '56',
          name: 'Mushroom Dosa',
          price: 85.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '57',
          name: 'Mushroom Masala Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '58',
          name: 'Mushroom Cheese Dosa',
          price: 105.0,
          category: 'Dosa',
        ),
        // Egg Dosas
        MenuItem(id: '59', name: 'Egg Dosa', price: 55.0, category: 'Dosa'),
        MenuItem(
          id: '60',
          name: 'Double Egg Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '61',
          name: 'Egg Masala Dosa',
          price: 75.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '62',
          name: 'Egg Onion Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '63',
          name: 'Egg Cheese Dosa',
          price: 90.0,
          category: 'Dosa',
        ),
        // Vegetable Dosas
        MenuItem(
          id: '64',
          name: 'Vegetable Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '65',
          name: 'Veg Masala Dosa',
          price: 80.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '66',
          name: 'Veg Cheese Dosa',
          price: 95.0,
          category: 'Dosa',
        ),
        // Special Dosas
        MenuItem(
          id: '67',
          name: 'Masala Roast Dosa',
          price: 80.0,
          category: 'Dosa',
        ),
        MenuItem(id: '68', name: 'Tomato Dosa', price: 55.0, category: 'Dosa'),
        MenuItem(
          id: '69',
          name: 'Tomato Masala Dosa',
          price: 70.0,
          category: 'Dosa',
        ),
        MenuItem(id: '70', name: 'Coconut Dosa', price: 60.0, category: 'Dosa'),
        MenuItem(
          id: '71',
          name: 'Coconut Masala Dosa',
          price: 75.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '72',
          name: 'Gunpowder Dosa',
          price: 55.0,
          category: 'Dosa',
        ),
        MenuItem(
          id: '73',
          name: '70mm Dosa (Family)',
          price: 150.0,
          category: 'Dosa',
        ),
        MenuItem(id: '74', name: 'Jini Dosa', price: 95.0, category: 'Dosa'),
        MenuItem(id: '75', name: 'Andhra Dosa', price: 65.0, category: 'Dosa'),
        MenuItem(
          id: '76',
          name: 'Andhra Masala Dosa',
          price: 80.0,
          category: 'Dosa',
        ),
        MenuItem(id: '77', name: 'Keema Dosa', price: 120.0, category: 'Dosa'),
        MenuItem(
          id: '78',
          name: 'Keema Masala Dosa',
          price: 130.0,
          category: 'Dosa',
        ),
      ];

      for (var item in defaultItems) {
        await _menuItemsBox!.put(item.id, item);
      }
    }

    // Initialize app config if empty
    if (_appConfigBox!.isEmpty) {
      await _appConfigBox!.put('config', AppConfig());
    }
  }

  // Menu Items - Return local data immediately for instant loading
  Future<List<MenuItem>> getMenuItems() async {
    // Return local data instantly (no API wait)
    final localItems = _menuItemsBox?.values.toList() ?? [];

    // Try API in background (don't wait for it)
    _syncWithApiInBackground();

    return localItems;
  }

  // Background API sync (fire and forget)
  void _syncWithApiInBackground() async {
    try {
      final apiItems = await ApiService.getMenuItems().timeout(
        const Duration(seconds: 1),
        onTimeout: () => [],
      );
      if (apiItems.isNotEmpty) {
        // Update local storage with API data
        for (var item in apiItems) {
          await _menuItemsBox?.put(item.id, item);
        }
      }
    } catch (e) {
      print('Background API sync failed: $e');
    }
  }

  Future<List<String>> getCategories() async {
    // Get local items instantly
    final items = _menuItemsBox?.values.toList() ?? [];
    if (items.isEmpty) return [];

    final categories = items.map((e) => e.category).toSet().toList();
    categories.sort();
    return categories;
  }

  Future<List<MenuItem>> getMenuItemsByCategory(String category) async {
    final items = await getMenuItems();
    return items.where((item) => item.category == category).toList();
  }

  Future<void> addMenuItem(MenuItem item) async {
    await _menuItemsBox?.put(item.id, item);
  }

  Future<void> updateMenuItem(MenuItem item) async {
    await _menuItemsBox?.put(item.id, item);
  }

  Future<void> deleteMenuItem(String id) async {
    await _menuItemsBox?.delete(id);
  }

  // App Config
  AppConfig getAppConfig() {
    return _appConfigBox?.get('config') ?? AppConfig();
  }

  Future<void> updateAppConfig(AppConfig config) async {
    await _appConfigBox?.put('config', config);
  }

  // Printer Config
  PrinterConfig? getPrinterConfig() {
    return _printerConfigBox?.get('printer');
  }

  Future<void> setPrinterConfig(PrinterConfig config) async {
    await _printerConfigBox?.put('printer', config);
  }

  Future<void> clearPrinterConfig() async {
    await _printerConfigBox?.delete('printer');
  }

  // Current Order (auto-save)
  List<OrderLine>? getCurrentOrder() {
    final order = _currentOrderBox?.get('order');
    if (order == null) return null;
    return List<OrderLine>.from(order);
  }

  Future<void> saveCurrentOrder(List<OrderLine> orderLines) async {
    await _currentOrderBox?.put('order', orderLines);
  }

  Future<void> clearCurrentOrder() async {
    await _currentOrderBox?.delete('order');
  }

  // Completed Orders
  List<Order> getCompletedOrders() {
    return _ordersBox?.values.toList() ?? [];
  }

  Future<void> saveCompletedOrder(Order order) async {
    await _ordersBox?.put(order.id, order);
  }
}
